// Move this file to /VirtualMachine/src so this can work on production

#include <vector>

#include <controller/classes/action.h>
#include <controller/classes/code.h>
#include <controller/classes/number.h>
#include <controller/classes/instruction.h>

#include <controller/classes/core.h>

#include <util/config.h>
#include <util/globals.h>

using namespace std;

int main() {
	//Settings
	Config::machine_health = 100;
	Config::machine_instructions_cycle = 50;
	Config::machine_melee_attack = 60;
	Config::machine_fuel = 100;
	Config::max_crystals_per_cell = 20;
	Config::machine_inst_fuel_usage = 0.01;
	Config::available_crystals = 120;
	Config::machine_mov_fuel_usage = 0;

	const vector<vector<int>> terrain {
		{1, 1, 3, 0, 2, 3, 1, 2, 3, 4, 0, 4, 0, 1, 0, 2, 3, 3, 2, 1}, 
		{2, 2, 2, 4, 3, 3, 2, 1, 3, 3, 4, 4, 2, 1, 2, 3, 2, 2, 3, 0}, 
		{3, 3, 2, 1, 1, 4, 1, 1, 0, 1, 2, 3, 4, 1, 0, 3, 4, 3, 3, 0}, 
		{3, 3, 1, 3, 3, 3, 4, 4, 1, 1, 2, 1, 4, 4, 4, 1, 3, 2, 0, 2}, 
		{1, 2, 2, 3, 3, 1, 2, 2, 4, 0, 1, 2, 3, 2, 4, 0, 4, 1, 0, 1}, 
		{2, 4, 0, 2, 4, 1, 1, 2, 1, 1, 2, 4, 0, 3, 2, 3, 0, 1, 2, 0}, 
		{2, 3, 1, 3, 3, 0, 0, 2, 0, 3, 0, 3, 3, 0, 1, 2, 4, 2, 0, 4}, 
		{2, 1, 0, 3, 1, 2, 3, 1, 4, 0, 2, 4, 0, 2, 2, 2, 4, 2, 3, 4}, 
		{4, 4, 0, 4, 3, 0, 2, 2, 3, 2, 4, 1, 0, 2, 2, 4, 4, 3, 3, 1}, 
		{2, 0, 4, 3, 1, 4, 0, 2, 2, 3, 0, 4, 4, 3, 4, 0, 1, 4, 2, 1}, 
	};

	arena.import_terrain(terrain);

	Army army1("Army 1");
	arena.insert_army(army1);

	Army army2("Army 2");
	arena.insert_army(army2);

	Army army3("Army 3");
	arena.insert_army(army3);

	Army army4("Army 4");
	arena.insert_army(army4);
	const vector<Instruction> prog1 ({
        Instruction(Code::JMP,make_shared<Number>(140))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::NE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(22))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::NE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::NW))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(45))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::NW))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::EA))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(68))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::EA))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::WE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(91))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::NE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::SW))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(114))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::SW))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::SE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(137))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::SE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::JIF,make_shared<Number>(198))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::WE))
        ,Instruction(Code::JIF,make_shared<Number>(151))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::NW))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(1))
        ,Instruction(Code::CALL,make_shared<Number>(1))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(143))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::NW))
        ,Instruction(Code::JIF,make_shared<Number>(160))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::NE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(1))
        ,Instruction(Code::CALL,make_shared<Number>(1))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(152))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::NE))
        ,Instruction(Code::JIF,make_shared<Number>(169))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::EA))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(1))
        ,Instruction(Code::CALL,make_shared<Number>(1))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(161))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::EA))
        ,Instruction(Code::JIF,make_shared<Number>(178))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::SE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(1))
        ,Instruction(Code::CALL,make_shared<Number>(1))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(170))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::SE))
        ,Instruction(Code::JIF,make_shared<Number>(187))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::SW))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(1))
        ,Instruction(Code::CALL,make_shared<Number>(1))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(179))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::SW))
        ,Instruction(Code::JIF,make_shared<Number>(196))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::WE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(1))
        ,Instruction(Code::CALL,make_shared<Number>(1))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(188))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(141))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::END,make_shared<Number>(0))
    });

	for(int i=0; i<3; i++)
		arena.create_robot(army2.get_id(), prog1);

	const vector<Instruction> prog2 ({
        Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::JIF,make_shared<Number>(141))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::NE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(23))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::NE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::NW))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(46))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::NW))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::EA))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(69))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::EA))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::WE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(92))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::NE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::SW))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(115))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::SW))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::SE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::NE,make_shared<Number>(0))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(138))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::ATKMELEE, Direction::SE))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::END,make_shared<Number>(0))
    });

	for(int i=0; i<7; i++)
		arena.create_robot(army3.get_id(), prog2);

	const vector<Instruction> prog3 ({
        Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::CE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::SEE, Direction::NE))
        ,Instruction(Code::STO,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(2))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::END,make_shared<Number>(0))
    });

	for(int i=0; i<1; i++)
		arena.create_robot(army4.get_id(), prog3);


	Core core(100);
	core.start();
}

