// Move this file to /VirtualMachine/src so this can work on production

#include <vector>

#include <controller/classes/action.h>
#include <controller/classes/code.h>
#include <controller/classes/number.h>
#include <controller/classes/instruction.h>

#include <controller/classes/core.h>

#include <util/config.h>
#include <util/globals.h>

using namespace std;

int main() {
	//Settings
	Config::machine_health = 100;
	Config::machine_instructions_cycle = 50;
	Config::machine_melee_attack = 20;
	Config::machine_fuel = 100;
	Config::max_crystals_per_cell = 20;
	Config::machine_inst_fuel_usage = 0.01;
	Config::available_crystals = 120;
	Config::machine_mov_fuel_usage = 1.5;

	const vector<vector<int>> terrain {
		{2, 3, 3, 2, 1, 0, 1, 2, 2, 3, 2, 4, 3, 1, 0, 4, 4, 2, 2, 3}, 
		{3, 1, 0, 3, 1, 0, 0, 0, 4, 2, 3, 0, 4, 3, 3, 0, 4, 3, 0, 3}, 
		{2, 0, 2, 3, 1, 2, 4, 2, 2, 4, 1, 3, 3, 3, 3, 3, 2, 3, 2, 4}, 
		{4, 4, 1, 0, 3, 4, 3, 0, 2, 1, 2, 0, 2, 3, 4, 0, 2, 3, 2, 4}, 
		{4, 3, 0, 3, 2, 2, 1, 2, 1, 3, 4, 0, 2, 1, 0, 0, 2, 4, 3, 2}, 
		{4, 2, 1, 0, 0, 0, 1, 0, 1, 1, 2, 3, 0, 3, 3, 3, 0, 4, 4, 2}, 
		{3, 4, 0, 2, 4, 1, 0, 0, 3, 2, 2, 0, 3, 1, 0, 0, 4, 0, 3, 0}, 
		{2, 3, 4, 1, 2, 2, 0, 3, 2, 0, 2, 1, 2, 3, 4, 2, 3, 1, 0, 3}, 
		{3, 0, 3, 0, 0, 1, 4, 0, 0, 3, 2, 0, 0, 4, 4, 1, 3, 0, 3, 4}, 
		{1, 2, 3, 4, 0, 0, 0, 2, 3, 4, 0, 0, 4, 1, 2, 1, 1, 0, 0, 0}, 
	};

	arena.import_terrain(terrain);

	Army army1("Army 1");
	arena.insert_army(army1);

	Army army2("Army 2");
	arena.insert_army(army2);
	const vector<Instruction> prog1 ({
        Instruction(Code::JMP,make_shared<Number>(31))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::WE))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(27))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::NW))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(26))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::SW))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(25))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(63))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::EA))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(59))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::SE))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(58))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::NE))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(57))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(88))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::NE))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(84))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::MOVE, Direction::NW))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(83))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(97))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::WE))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::SW))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::NW))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::EA))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::SE))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::COLLECT, Direction::NE))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(112))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::STO,make_shared<Number>(1))
        ,Instruction(Code::RCL,make_shared<Number>(1))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::LT,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(110))
        ,Instruction(Code::RCL,make_shared<Number>(1))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::ADD,make_shared<Number>(0))
        ,Instruction(Code::STO,make_shared<Number>(1))
        ,Instruction(Code::JMP,make_shared<Number>(101))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(130))
        ,Instruction(Code::RCL,make_shared<Number>(0))
        ,Instruction(Code::ATR,make_shared<Number>(3))
        ,Instruction(Code::MATR,make_shared<Number>(1))
        ,Instruction(Code::EQ,make_shared<Number>(0))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(124))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JIT,make_shared<Number>(128))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(146))
        ,Instruction(Code::ENTRY,make_shared<Number>(0))
        ,Instruction(Code::CALL,make_shared<Number>(114))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(140))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JIT,make_shared<Number>(144))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(161))
        ,Instruction(Code::ENTRY,make_shared<Number>(0))
        ,Instruction(Code::CALL,make_shared<Number>(114))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(159))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::SYS,make_shared<Action>(SystemCode::DROP, Direction::CE))
        ,Instruction(Code::JIF,make_shared<Number>(158))
        ,Instruction(Code::MATR,make_shared<Number>(4))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(153))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::RET,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::JIF,make_shared<Number>(265))
        ,Instruction(Code::ENTRY,make_shared<Number>(8))
        ,Instruction(Code::CALL,make_shared<Number>(33))
        ,Instruction(Code::JIF,make_shared<Number>(172))
        ,Instruction(Code::ENTRY,make_shared<Number>(8))
        ,Instruction(Code::CALL,make_shared<Number>(90))
        ,Instruction(Code::MATR,make_shared<Number>(4))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(164))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(2))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::STO,make_shared<Number>(8))
        ,Instruction(Code::RCL,make_shared<Number>(8))
        ,Instruction(Code::JIF,make_shared<Number>(199))
        ,Instruction(Code::ENTRY,make_shared<Number>(9))
        ,Instruction(Code::CALL,make_shared<Number>(132))
        ,Instruction(Code::STO,make_shared<Number>(9))
        ,Instruction(Code::ENTRY,make_shared<Number>(10))
        ,Instruction(Code::CALL,make_shared<Number>(1))
        ,Instruction(Code::STO,make_shared<Number>(10))
        ,Instruction(Code::RCL,make_shared<Number>(9))
        ,Instruction(Code::RCL,make_shared<Number>(10))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::STO,make_shared<Number>(8))
        ,Instruction(Code::ENTRY,make_shared<Number>(11))
        ,Instruction(Code::CALL,make_shared<Number>(90))
        ,Instruction(Code::STO,make_shared<Number>(11))
        ,Instruction(Code::PUSH,make_shared<Number>(3))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(179))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::PUSH,make_shared<Number>(4))
        ,Instruction(Code::PUSH,make_shared<Number>(-1))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::PRN,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(114))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(212))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(148))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JIT,make_shared<Number>(263))
        ,Instruction(Code::PUSH,make_shared<Number>(0))
        ,Instruction(Code::STO,make_shared<Number>(11))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::STO,make_shared<Number>(8))
        ,Instruction(Code::RCL,make_shared<Number>(8))
        ,Instruction(Code::JIF,make_shared<Number>(232))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(132))
        ,Instruction(Code::STO,make_shared<Number>(9))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(65))
        ,Instruction(Code::STO,make_shared<Number>(10))
        ,Instruction(Code::RCL,make_shared<Number>(9))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(10))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::STO,make_shared<Number>(8))
        ,Instruction(Code::JMP,make_shared<Number>(218))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(114))
        ,Instruction(Code::DUP,make_shared<Number>(0))
        ,Instruction(Code::JIF,make_shared<Number>(241))
        ,Instruction(Code::POP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(148))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JIT,make_shared<Number>(260))
        ,Instruction(Code::PUSH,make_shared<Number>(1))
        ,Instruction(Code::STO,make_shared<Number>(8))
        ,Instruction(Code::RCL,make_shared<Number>(8))
        ,Instruction(Code::JIF,make_shared<Number>(259))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(132))
        ,Instruction(Code::STO,make_shared<Number>(9))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(33))
        ,Instruction(Code::STO,make_shared<Number>(10))
        ,Instruction(Code::RCL,make_shared<Number>(9))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(10))
        ,Instruction(Code::MUL,make_shared<Number>(0))
        ,Instruction(Code::STO,make_shared<Number>(8))
        ,Instruction(Code::JMP,make_shared<Number>(245))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::ENTRY,make_shared<Number>(12))
        ,Instruction(Code::CALL,make_shared<Number>(148))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::JMP,make_shared<Number>(162))
        ,Instruction(Code::NOP,make_shared<Number>(0))
        ,Instruction(Code::END,make_shared<Number>(0))
    });

	for(int i=0; i<1; i++)
		arena.create_robot(army1.get_id(), prog1);


	Core core(100);
	core.start();
}

